apiVersion: 1
datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: false
    jsonData:
      timeField: "@timestamp"
      esVersion: 8
