apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        tags:
          - key: trace_id
            value: ${__trace.traceId}
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{trace_id="${__trace.traceId}"}'
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: '1m'
        spanEndTimeShift: '-1m'
        tags:
          - key: service.name
            value: '${__span.tags.service.name}'
        queries:
          - name: 'Request Rate'
            query: 'rate(http_server_requests_total{service="${__span.tags.service.name}"}[1m])'
